### ISSUE TITLE
remote connection

### ISSUE THREAD

**Issue by samanemami** [pathwaycom/llm-app#71]
### Steps to reproduce

I am using this repository in a remote mode using ssh and pem key, therefore, I can not use a local address for UI.
Is there any approach to skip the URL part of the curl command or force it to run without opening the URL?

Thank you 

### Relevant log output

```text
Connection time out
```

### What did you expect to happen?

Run the program without opening url

### Version

current main version

### OS

Linux

### On which CPU architecture did you run Pathway?

x86-64

**Comment by dxtrous** [comment]
Hi @samanemami, for production, you need to be able to connect to the machine you are running the backend on via TCP, otherwise you will not be able to run this specific setup.
If you have SSH access to the machine, you should in principle be able to connect to it from an SSH session on the same machine with `curl` as you propose, using the local loopback address for IP (127.0.0.1) and the port indicated when launching the server.
